; Generated by AniDB on <tmpl_var name=global_date>
; http://anidb.info/
<tmpl_loop name=loop_anime>
;<tmpl_var name=data_anime_name><tmpl_loop name=loop_ep><tmpl_loop name=loop_file>
<tmpl_var name=data_ep_epno> <tmpl_var name=data_file_crc></tmpl_loop></tmpl_loop>
</tmpl_loop>