/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class epox_av_AVInfo */

#ifndef _Included_epox_av_AVInfo
#define _Included_epox_av_AVInfo
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     epox_av_AVInfo
 * Method:    version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_epox_av_AVInfo_version
  (JNIEnv *, jclass);

/*
 * Class:     epox_av_AVInfo
 * Method:    fileOpen
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_epox_av_AVInfo_fileOpen
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     epox_av_AVInfo
 * Method:    fileParse
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_epox_av_AVInfo_fileParse
  (JNIEnv *, jobject, jlong);

/*
 * Class:     epox_av_AVInfo
 * Method:    fileClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_epox_av_AVInfo_fileClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     epox_av_AVInfo
 * Method:    fileFormatted
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_epox_av_AVInfo_fileFormatted
  (JNIEnv *, jobject, jlong, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
